Zmiany
t0meck-pj/sop2021-22_25c pull request #10
Opened 2022-03-30 22:54 UTC by s25938pj

-Poprawiłem 1szą część do pana komentarzy i nie jestem pewny jedynie możliwych miejsc instalacji GRUB-a w obrębie 1 dysku
-Przeczytałem dokładnie plik readme i stworzyłem taką strukturę jaką pan opisywał (w pamietniku tylko przemyslenia i co się nauczyłem, a reszta zadań zgodnie z wytycznymi)
-Przemyśleń odnośnie 2 laboratorium nie jestem za bardzo w stanie opisać, ponieważ nie było mnie na tym zjeździe, z powodu spraw prywatnych.

2022-04-19 19:29 UTC, t0meck-pj requested changes
Proszę poprawić swóją zmianę. W miejscach gdzie zostawiłem komentarze dodać inforomację co zostało zmienione. Sprawdzę wtedy nierozwiązane problemy.

2022-04-22 09:56 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +Wybieramy rozmiar pamięci RAM jaki chcemy wykorzystywać w naszej maszynie
Wybieramy rozmiar pamięci RAM jaki chcemy wykorzystywać w naszej maszynie. Do odpalenia podstawowej dystrybucji linuxa wystarczy 1024mb, natomiast podczas poważnej pracy będzie to zdecydowanie za małego
Na stronie debiana możemy znaleźć że minimalne wymagania w przypadku braku pulpitu to 128mb a zalecane to 512mb
natomiast w przypadku komputera stacjonarnego z graficznym interfejsem minimalna ilość ramu to 256mb a zalecana to 1gb
My z racji że chcemy aby nasza maszyna była wydajna wybieramy 4096mb

2022-04-22 10:04 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +Mamy 3 możliwości w zakładce "Dysk Twardy"
-Nie dodawaj wirtualnego dysku twardego - stworzymy wtedy maszynę bez dysku która się nie odpali (wybieramy gdy nie chcemy tworzyc wirtualnego dysku oraz nie mamy go również jeszcze pobranego)
-Stwórz wirtualny dysk twardy - Przechodzimy przez dalszą konfigurację gdzie konfigurujemy parametry wirtualnego dysku(wybieramy gdy nie mamy pobranego pliku z wirtualnym dyskiem) (KLIKAMY W TĄ OPCJE)
-Użyj istniejącego pliku wirtualnego dysku twardego - (używamy gdy mamy na komputerze pobrany plik z wirtualnym dyskiem o formacie vdi i chcemy go użyć)

Nie jestem pewny opcji niedodawania wirtualnego dysku

2022-04-22 10:05 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +-Stwórz wirtualny dysk twardy - Przechodzimy przez dalszą konfigurację gdzie konfigurujemy parametry wirtualnego dysku (KLIKAMY W TĄ OPCJE)
-Stwórz wirtualny dysk twardy - Przechodzimy przez dalszą konfigurację gdzie konfigurujemy parametry wirtualnego dysku(wybieramy gdy nie mamy pobranego pliku z wirtualnym dyskiem) (KLIKAMY W TĄ OPCJE, ponieważ nie mamy pliku vdi a jedynie plik iso z instalką systemu który chcemy zainstalować na naszej maszynie)

2022-04-22 10:11 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +-Nie dodawaj wirtualnego dysku twardego -
-Nie dodawaj wirtualnego dysku twardego - stworzymy wtedy maszynę bez dysku która się nie odpali (wybieramy gdy nie chcemy tworzyc wirtualnego dysku oraz nie mamy go również jeszcze pobranego.
 Jest to opcja przydatna w przypadku gdy mamy maszynę portable i system zainstalowany na przenośnym dysku (podłączamy dysk kiedy tego potrzebujemy))

Również nie jestem pewny czy o to chodziło

2022-04-22 10:17 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +-Dynamiczny Rozmiar - Ustawiamy rozmiar do którego maksymalnie będzie się mógł zwiększać nasz wirtualny dysk (Wybieramy tą opcję)
-Dynamiczny Rozmiar - Ustawiamy rozmiar do którego maksymalnie będzie się mógł zwiększać nasz wirtualny dysk (Wybieramy tą opcję, z racji iż na początku nasz dysk będzie zajmował mało miejsca na fizycznym dysku
i nie zajmie miejsca na nieużywane sektory dysku. Minusem tego rozwiązania natomiast jest zużywanie mocy obliczeniowej podczas rozszerzania dysku (czego nie ma w przypadku stałego rozmiaru))

2022-04-22 10:18 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +Zapisujemy ustawienia i możemu już uruchomić naszą maszynę.
Zapisujemy ustawienia , natomiast musimy jeszcze zmienić parę rzeczy w konfiguracji naszej maszyny, więc jeszcze jej nie odpalamy.

2022-04-22 10:20 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +W zakładce Dźwięk wyłaczamy wyjście Aurdio (odznaczamy Enable Audio Output, ponieważ dźwięk nie będzie nam potrzebny w procesie instalacji systemu)
W zakładce Dźwięk wyłaczamy wyjście Aurdio (odznaczamy Enable Audio Output, ponieważ dźwięk nie będzie nam potrzebny w procesie instalacji systemu,
natomiast jeżeli będziemy chcieli instalować system z syntezatorem głosu, lub będziemy po instalacji oglądać jakieś rzeczy na youtube, lub słuchać muzyki, to będziemy musieli po instalacji
uruchomić tą opcję)

2022-04-22 10:21 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +Odznaczanie/Usuwanie urządzeń jest zalecane w przypadku kiedy nie mamy urządzenia (jak naprzykład stacja dyskietek) i wiemy że napewno nie będziemy z
Odznaczanie/Usuwanie urządzeń jest zalecane w przypadku kiedy nie mamy urządzenia (jak naprzykład stacja dyskietek) i wiemy że napewno nie będziemy z 
tego korzystać w przyszłości. Jest to zalecane, ponieważ oszczędzamy wtedy moc obliczeniową naszej maszyny, która nie będzie wykorzystywana na nieużywane funkcje

2022-04-22 10:27 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +nie będzie posiadał tłumaczenia na dany język, mogą się nam pojawiać "⬜︎", a jak wiadomo język angielski jest powszechnie używany w IT
Tak Panie Profesorze. Natomiast jeżeli mamy ustawiony system w języku angielskim, a będziemy chcieli używać liter z języka polskiego (takich jak ą,ę,ć,ó,ł) to mogą być one niewidoczne (jest tak bynajmniej na windowsie. Nie mogę znaleźć nigdzie informacji jak jest na dystrybucjach linuxa)

2022-04-22 10:31 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +-Configure ISCII volumes - Konfiguracja woluminów ISCII (ISCII - schemat kodowania reprezentujący różne systemy pisma w Indiach)
-Configure ISCII volumes - Konfiguracja woluminów ISCSI (ISCSI - Technika umożliwiająca wykonywanie operacji wejścia-wyjścia na dysku twardym odległej maszyny za pomocą protokołu TCP/IP. 
Źródło: https://pl.wikipedia.org/wiki/ISCSI)

2022-04-22 10:43 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +-Manual - Ręczne partycjonowanie dysków (wybieramy tą opcje)
-Manual - Ręczne partycjonowanie dysków (wybieramy tą opcje, ponieważ mamy wtedy większe pole do popisu jeżeli chodzi o partycjonowanie dysków
Korzyściami tej opcji jest m.in. możliwość zachowania plików instalacji systemu osobno, możliwość wydzielenia oddzielnej partycji na kopię zapasową, pomaga chronić nasze pliki przed 
złośliwym oprogramowaniem oraz daje możliwość łatwego zarządzania. Dodatkowo jest to przydatne w przypadku instalacji 2 lub więcej systemów, gdzie na każdy system wydzielamy osobną partycję)
Wadami tej opcji jest natomiast m.in fałszywe poczucie bezpieczeństwa (w razie awarii nadal tracimy dane ze wszystkich partycji), nie poprawia to naszej wydajności, w przypadku dużej aktualizacji
systemu może dojść do sytuacji, gdzie na partycji systemowej nie będziemy mieli miejsca, a inna będzie miała tego miejsca sporo, oraz jest to nieprzydatne dla przeciętnego użytkownika, który
nie posiada dużej ilości plików oraz chęci ich zarządzania, oraz nie posiada innych systemów operacyjnych poza jednym
Następnie wyskakuje 5 opcji

2022-04-22 10:55 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +- Guided-use entire disk - Przypisywanie 1 partycji na całym dysku
---Okno instalacji---
Wyskakuje okno partycjonowania dysków
- Guided-use entire disk - Przypisywanie 1 partycji na całym dysku (wybieramy, gdzy zależy nam na czasie i nie chcemy się bawić w ręczne partycjonowanie. Opcja ta usunie wszystkie wcześniej
utworzone partycje oraz pliki(jest to więc przydatne w przypadku formatowania komputera i stawiania świeżego systemu))
- Guided-use entire disk and set up LVM - Przypisywanie 1 partycji na całym dysku i ustawienie LVM (jest to przydatne, gdy potrzebujemy wielu partycji na wielu dyskach oraz daje nam możliwość
połaczenie partycji z kilku dysków w jeden wirualny dysk. Dodatkowo w przypadku wybrania tej opcji musimy wybrać czy chemy aby nasze woluminy mają być zaczyfrowane za pomocą luks(specyfikacja 
szyfrowania dysky twardego przeznaczona dla linux), oraz w przypadku wybrania szyfrowania należy podać hasło, które będziemy wprowadzać przy uruchomieniu systemu)
	(LVM-softwareowa implementacja RAIDA( WIĘCEJ INFORMACJI O RAIDZIE NA SAMYM DOLE))
- Guided-use entire disk and set up encrypted LVM - Przypisywanie 1 partycji na całym dysku i ustawienie szyfrowanego LVM
-Manual - Ręczne partycjonowanie dysków (wybieramy tą opcje, ponieważ mamy wtedy większe pole do popisu jeżeli chodzi o partycjonowanie dysków
Korzyściami tej opcji jest m.in. możliwość zachowania plików instalacji systemu osobno, możliwość wydzielenia oddzielnej partycji na kopię zapasową, pomaga chronić nasze pliki przed 
złośliwym oprogramowaniem oraz daje możliwość łatwego zarządzania. Dodatkowo jest to przydatne w przypadku instalacji 2 lub więcej systemów, gdzie na każdy system wydzielamy osobną partycję)
Wadami tej opcji jest natomiast m.in fałszywe poczucie bezpieczeństwa (w razie awarii nadal tracimy dane ze wszystkich partycji), nie poprawia to naszej wydajności, w przypadku dużej aktualizacji
systemu może dojść do sytuacji, gdzie na partycji systemowej nie będziemy mieli miejsca, a inna będzie miała tego miejsca sporo, oraz jest to nieprzydatne dla przeciętnego użytkownika, który
nie posiada dużej ilości plików oraz chęci ich zarządzania, oraz nie posiada innych systemów operacyjnych poza jednym

2022-04-22 10:57 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +-Configure Software Raid - Konfiguracja RAID-a
poprawione

2022-04-22 11:56 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +-Configure the Logical Volume Manager - Konfiguracja Menedżera woluminów logicznych
różnica między RAID i LVM polega na tym, że LVM nie zapewnia żadnych opcji redundancji ani parzystości, które zapewnia macierz RAID (Żródło: https://computingforgeeks.com/raid-vs-lvm-vs-zfs-comparison/)

2022-04-22 11:59 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +Wyskakują poza wcześniejszymi opjcami 3 nowe
Wyskakują poza wcześniejszymi opjcami 3 nowe
-Configure Software Raid - Konfiguracja RAID-u (wybieramy gdy mamy więcej niż 1 dysk i chcemy utowrzyć macierz RAID która da nam możliwość zwiększenia prędkości lub bezpieczeństwo w razie awarii jednego z dysków)
różnica między RAID i LVM polega na tym, że LVM nie zapewnia żadnych opcji redundancji ani parzystości, które zapewnia macierz RAID (Żródło: https://computingforgeeks.com/raid-vs-lvm-vs-zfs-comparison/)
-Configure the Logical Volume Manager - Konfiguracja Menedżera woluminów logicznych (wyżej wspomniany LVM, wybieramy gdy mamy kilka dysków i chcemy je połączyć w jeden wirtualny)
-Configure encrypted manager - Konfiguracja menadżera Szyfrowania (Wybieramy gdy chcemy aby nasze pliki były zaszyfrowane za pomocą AES lub Twofish)

2022-04-22 12:00 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +Wybieramy zakładkę z wolnym miejscem na naszej partycji
Wybieramy zakładkę z wolnym miejscem na naszej partycji, ponieważ w naszym przypadku nie będziemy konfigurować żadnej z powyższych opcji

2022-04-22 12:32 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +-Create a new partition - Tworzenie nowej partycji(WYBIERAMY TĄ OPCJE)
-Create a new partition - Tworzenie nowej partycji(WYBIERAMY TĄ OPCJE, ponieważ chcemy skonfigurować naszą partycję zgodnie z naszymi potrzebami)

2022-04-22 12:33 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +-Automatically partition the free space - Automatyczne tworzeniej partycji na wolnym miejscu
-Automatically partition the free space - Automatyczne tworzeniej partycji na wolnym miejscu (Jest ona pomocna w przypadku gdy mamy już utworzone nasze partycję, natomiast zostało
nam wolne miejsce na dysku, a w przypadku nieprzypisania go do żadnej partycji miejsce pójdzie na zmarnowanie)

2022-04-22 13:03 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +Ustawiamy partycję podstawową o pojemności o 8GB Mniejszą od tej pamięci jaka nam wyskakuje (Aby mieć miejsce potem na logiczną), ustawiamy ją na początku (Beginning)
Ustawiamy partycję podstawową o pojemności o 8GB Mniejszą od tej pamięci jaka nam wyskakuje (Aby mieć miejsce potem na logiczną), ustawiamy ją na początku (Beginning)
Wybieramy podstawową dlatego, iż do uruchomienia systemu musimy posiadać conajmniej jedną partycję podstawową (maksymalnie można mieć 4)
Wartość 8GB wzięła się stąd, iż reszte pamięci musimy poświęcić na partycję logiczną (tzw. LPAR) która umożliwia uruchamianie własnej kopii systemu operacyjnego.
Partycji logicznych możemy mieć nieograniczona ilość na naszym dysku

2022-04-22 13:16 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +Ext4 journaling file system - Następca ext3. Obecnie najpopularniejszy system plików dla systemów Linuxa.
xt4 journaling file system - Następca ext3. Obecnie najpopularniejszy system plików dla systemów Linuxa.
jest on dużo wydajniejszy oraz posiada kompatybliność wsteczną względem ext3. Możemy m.in wyłączyć w nim funkcję księgowania, co poprawi wydajność,
Limit systemu plików został zwiększony z 16TB do 1EB  (1EB = 1024PB, 1PB = 1024TB), limit plików z 2TB do 16TB, limit podkatalogów został rozszerzony z 32,768 do nieograniczonego,

2022-04-22 13:21 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +-Use as - używaj jako (domyślnie system plików ext4)
-Use as - używaj jako (domyślnie system plików ext4. Wybieramy go dlatego iż aktualnie jest najbardziej solidny i stabilny. Według informacji na internecie
w przyszłości dystrybucje linuxa będą stopniowo przesuwać się w kierunku BtrFS)

2022-04-22 13:25 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +Ustawiamy partycję podstawową o pojemności o 8GB Mniejszą od tej pamięci jaka nam wyskakuje (Aby mieć miejsce potem na logiczną), ustawiamy ją na początku (Beginning)
Ustawiamy partycję podstawową o pojemności o 8GB Mniejszą od tej pamięci jaka nam wyskakuje (Aby mieć miejsce potem na logiczną), ustawiamy ją na początku (Beginning)
Wybieramy podstawową dlatego, iż do uruchomienia systemu musimy posiadać conajmniej jedną partycję podstawową (maksymalnie można mieć 4)
Wartość 8GB wzięła się stąd, iż drugą partycję (logiczną) ustawimy na swap area (tzw. fałszywa pamięć ram) która jest wolniejsza niż rzeczywista pamięć RAM. Zalecane jest ustawienie partycji swap area o takiej samej pojemności jak nasz RAM. a z racji iż RAM ustawiliśmy na 8GB to swap area również ustawiamy na 8GB
Partycji logicznych możemy mieć nieograniczona ilość na naszym dysku

2022-04-22 13:51 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +-Bootable flag - flaga startowa (off)
1.Jest to 1 - bajtowa wartość w nierozszerzonym rekordzie partycji w głównym rekordzie rozruchowym . 
Pojawia się na początku rekordu partycji jako wartość 0x80. Wartość 0x00 wskazuje, że partycja nie ma ustawionej flagi rozruchu.
Każda inna wartość jest nieprawidłowa. (Źródło: https://en.wikipedia.org/wiki/Boot_flag)
2.Wybieramy że nie, ponieważ jest to przestarzała metoda a MBR poosiada moduł ładujący który ładuje się do własnej partycji lub przeskakuje do innych dysków.
3.Flaga powinna być ustawiona gdy chcemy wskazać rekord partycji MBR
4.Ustawia się ją aby załadować ten program znajdujący się na partycji MBR
5.Może być ona ustawiona tylko na jednej partycji, ponieważ w przeciwnym wypadku mamy gwarantowany konflikt (komputer nie będzie wiedział którą partycję ma zbootować)
6.Ograniczeniem jest to, że możemy miec ustawioną jedną flagę., ponieważ w przeciwnym przypadku tak jak powyżej będziemy mieli konflikt

2022-04-22 14:39 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +Mamy już utworzoną pierwszą partycję podstawową . Klikamy znowu w zakładkę free space/create a new partition/przypisujemy 8GB i ustawiamy partycję tym razem na logiczną
Mamy już utworzoną pierwszą partycję podstawową . Klikamy znowu w zakładkę free space/create a new partition/przypisujemy 8GB i ustawiamy partycję tym razem na logiczną
ustawiamy teraz logiczną, ponieważ będziemy mieli w przyszłości możliwość rozszerzania partycji rozszerzonej o kolejne logiczne partycje (co nie jest dostępne przy podstawowej)
Partycja podstawowa jest przeznaczona do przechowywania plików systemu, innych danych oraz jest niezbędna do uruchomienia systemu
Partycja logiczna jest natomiast przeznaczona jedynie do przechowywania danych, ponieważ nie obsługują one systemu operacyjnego
Partycja Logiczna od podstawowej różni się tym, że w przypadku starych programów MBR mogł on się uruchomić tylko z poziomu partycji podstawowej. Oraz możemy na dysku 
mieć 4 partycję podstawowe i ani jednej logicznej, lub 3 partycje podstawowe i jedną partycję rozszerzoną, którą możemy podzielić na dowolną liczbę partycji logicznych

2022-04-22 14:53 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +swap area - obszar wymiany (Jest to tzw. fałszywa pamięć ram. która znajduje się na dysku. Dobrze jest mieć tyle miejsca do wymiany co faktyczna pamięć ram(Przechowuje tam wszystkie dane))(TEGO UŻYWA
swap area - obszar wymiany (Jest to tzw. fałszywa pamięć ram. która znajduje się na dysku.(Przechowuje tam wszystkie dane))(TEGO UŻYWAMY, 
ponieważ będzie nam to potrzebne w razie późniejszej hibernacji systemu(dane z pamięci RAM zapisują się tu, więc należy ustawić rozmiar
swap area na taki sam ile mamy RAM-u)

2022-04-22 15:01 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +Wyskakuje okno czy chcemy wziąć udział w ankiecie użytkowania pakietów(klikamy nie)
Wyskakuje okno czy chcemy wziąć udział w ankiecie użytkowania pakietów(klikamy nie)
Ankieta służy do przesyłania anonimowych informacji na temat używanych przez nas pakietach/programach. 
Powinniśmy wziąć w nim udział, gdy chcemy dostać płytę instalacyjną z pakietami 
Nie bierzemy aktualnie udziału w konkursie, ponieważ w razie potrzeby jakiegoś progamu/pakietu możemy go w kazdej chwili zainstalować

2022-04-22 15:57 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +Wyskakuje okno czy chcemy stworzyć nową pustą partycję na naszym urządzeniu (KLIKAMY YES)
Wyskakuje okno czy chcemy stworzyć nową pustą partycję na naszym urządzeniu (KLIKAMY YES)
Zapytanie wyskakuje ponieważ jest to zabezpieczenie. W razie iż gdybyśmy mieli już zapisane jakieś dane to przepadły by one. Z racji iż mamy pusty dysk klikamy tak
Nie przejdziemy przez dalszy proces, ponieważ mamy pusty nieskonfigurowany dysk bez żadnego systemu (jedyne wyjście to podłączenie skonfigurowanego pliku vdi w ustawieniach maszyny).
Opcja powoduje pojawienie się kolejnych opcji konfiguracji naszego dysku

Jeżeli chodzi o kwestię jaki jest powód pytania to nie mam pojęcia panie Profesorze. Podejrzewam że jest to coś podchwytliwego

2022-04-22 18:39 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia2/praca_domowa.txt
> +zmienna2=$(echo $zmienna1 | sed 's/\Jakub\>/\\e[31mJakub\\e[0m/g')
#!/bin/bash
echo -e "cat $1 | sed 's/\Jakub\>/\\e[31mJakub\\e[0m/g'"

2022-04-22 18:41 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia2/zadanie2.txt
> +Aby naprawić błąd musimy naszą zmienną zapisać w ""
Aby naprawić błąd musimy naszą zmienną zapisać w "", w '', lub zapisać jako jedno słowo

2022-04-22 18:43 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia2/zadanie3.txt
> +-PATH 	- Pokazuje ścieżki do komend- umożliwia dodanie skryptu do ścieżki z dowolnego miejsca export PATH(nazwa)=<ścieżka>
-PATH 	- Pokazuje ścieżki do komend- umożliwia dodanie skryptu do ścieżki z dowolnego miejsca export PATH=$PATH:/<ścieżka>

2022-04-22 18:50 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia2/zadanie3.txt
> +-PS1		- Wyświetla wartości konsoli
-PS1		- Zmienna która definiuje wygląd i styl wiersza poleceń

2022-04-22 19:46 UTC, t0meck-pj requested changes
Wprowadź proszę poprawki do opisu instalacji debiana oraz ustosunkuj się do reszty komentarzy z pozostałych plików.

2022-04-22 19:46 UTC, t0meck-pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +Odznaczanie/Usuwanie urządzeń jest zalecane w przypadku kiedy nie mamy urządzenia (jak naprzykład stacja dyskietek) i wiemy że napewno nie będziemy z
Jak odznaczenie urządzeń dodanych do kolejki bootowania ma zaoszczędzić moc obliczeniową?
To nie ma sensu. Powód jest inny. Bardziej trywialny.

2022-04-22 19:46 UTC, t0meck-pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +nie będzie posiadał tłumaczenia na dany język, mogą się nam pojawiać "⬜︎", a jak wiadomo język angielski jest powszechnie używany w IT
Tak tylko to nie ten etap instalacji. Tu wybierasz w język samego instalatora (który potem także będzie domyślnym językiem systemu) a nie kodowanie znaków. Kodowanie znaków i to o czym piszesz jest ustawiane później. Nie mieszaj tych pojęć ze sobą.
W ramach doświadczenia możesz spróbować wybrać instalację po angielsku jednak z polskim układem klawiatury. Czyli pierwszy wybór języka na angielski a reszta na polski.

2022-04-22 19:46 UTC, t0meck-pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +Wyskakuje okno czy chcemy stworzyć nową pustą partycję na naszym urządzeniu (KLIKAMY YES)
Partycje są zapisane w tablicy partycji. Skoro chcesz stworzyć partycję to musisz posiadać tablicę partycji. Skoro jej nie ma i nie wyrażasz zgodny na utworzenie tablicy partycji to nie da się stworzyć partycji bo nie będzie miejsca gdzie można by zapisać informację o tejże partycji. Za każdym razem kiedy tworzysz nową tablicę partycji tracisz informację o partycjach, które mogą być zapisane na dysku bo nowa tablica partycji będzie pusta.
Poza tym tablica partycji także ma swoje ograniczenia dlatego można utworzyć tylko 4 partycje podstawowe z czego 4-ta może być partycją rozszerzoną zawierającą kolejne partycje logiczne. Wtedy partycja rozszerzona dostaje numer 4, którego normalnie nie widać a pierwsza partycja logiczna dostaje numer 5 gdyż jest kolejną partycją na dysku za poza partycjami podstawowymi. Można stworzyć tylko 4 partycje podstawowe gdyż pole przechowujące numer partycji jest 2bitowe czyli wartości 00,01,10,11. To z tego wynika.

2022-04-22 19:46 UTC, t0meck-pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +- Guided-use entire disk - Przypisywanie 1 partycji na całym dysku (wybieramy, gdzy zależy nam na czasie i nie chcemy się bawić w ręczne partycjonowanie. Opcja ta usunie wszystkie wcześniej
Czy rzeczywiście jesteś pewien, że jedyne co ta opcja zrobi to utworzy jedną partycję? (czyt. nie)
I naprawdę nie ma tam kolejnego menu, które pokazuje kolejne opcje? (czyt. jest/są)

2022-04-22 19:46 UTC, t0meck-pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +Ustawiamy partycję podstawową o pojemności o 8GB Mniejszą od tej pamięci jaka nam wyskakuje (Aby mieć miejsce potem na logiczną), ustawiamy ją na początku (Beginning)
To sprawdź jeszcze raz ile ramu zostało przypisane do maszyny na początku opisu (linia 7).

2022-04-22 19:46 UTC, t0meck-pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +-Bootable flag - flaga startowa (off)
6 - nie ile tylko gdzie. Tu chodziło o to, że tylko na partycjach podstawowych można. Na logicznych nie.

2022-04-22 19:46 UTC, t0meck-pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +Ext4 journaling file system - Następca ext3. Obecnie najpopularniejszy system plików dla systemów Linuxa.
Dla wszystkich systemów plików a nie tylko pierwszego

2022-04-22 19:46 UTC, t0meck-pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +Wyskakuje okno czy chcemy wziąć udział w ankiecie użytkowania pakietów(klikamy nie)
Twój opis jest błędny.

Ankieta jest po to by wytypować listę pakietów, które zostaną wrzucone na obraz płyt instalacyjnych. Mniej popularne wcale się tam nie znajdują lub są umieszczane na płytach z dodatkowym, niepopularnym oprogramowaniem.

W ankiecie nie bierzesz udziału bo instalujesz system testowy więc branie udziału w konkursie nie ma sensu i dostarczało by błędnych danych statystycznych do autorów systemu.

2022-04-22 19:46 UTC, t0meck-pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +	Moc procesora 800 MHz (1 GHz dla optymalnej wydajności)
Moc -> Taktowanie

2022-04-22 19:46 UTC, t0meck-pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +	oraz nadaję się również dla słabszych komputerów. Jeżeli chodzi o wydajność i zużycie mocy obliczeniowej jest ono na średnim poziomie. Dodatkowo
Skoro KDE jest na średnim poziomie to znaczy, że GNOME, który obciąża system na wysokim poziomie powinien mieć wyższe wymagania sprzętowe... a jest odwrotnie.
Sprawdź i popraw opisy środowisk graficznych by były spójne.

2022-04-22 19:46 UTC, t0meck-pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +	Minimalne wymagania:
Te wymagania minimalne nadal są wyższe niż wymienione w minimalnych do Gnome.

2022-04-22 19:46 UTC, t0meck-pj commented on s25938pj-JakubKwasniak/zajecia2/praca_domowa.txt
> +zmienna2=$(echo $zmienna1 | sed 's/\Jakub\>/\\e[31mJakub\\e[0m/g')
Nie o to chodzi. Zobacz jak sedowi podać plik na wejście zamiast strumienia

2022-04-22 19:46 UTC, t0meck-pj commented on s25938pj-JakubKwasniak/zajecia2/zadanie3.txt
> +-PATH 	- Pokazuje ścieżki do komend- umożliwia dodanie skryptu do ścieżki z dowolnego miejsca export PATH(nazwa)=<ścieżka>
Już lepiej. Tylko jeszcze to powinno być w treści pliku

2022-04-22 19:52 UTC, t0meck-pj commented
> Wszystkie powyżej wprowadzone zmiany wprowadziłem oraz zrobiłem git pusha, natomiast po wejściu w pr nie mogę utworzyć nowego pr

Prawidłowo. Bo poprzedniego PR nie zamknąłem. Stwierdziłem, że taki sposób sprawdzania będzie wygodniejszy bo wtedy widzę swoje poprzednie komentarze i nie czytam za każdym razem całości tekstu. Ty musisz tylko zacommitować swoje zmiany a one automatycznie są uwzględniane w już otwartym PR.

2022-05-02 17:11 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +-Nie dodawaj wirtualnego dysku twardego - stworzymy wtedy maszynę bez dysku która się nie odpali (wybieramy gdy nie chcemy tworzyc wirtualnego dysku oraz nie mamy go również jeszcze pobranego.
-Nie dodawaj wirtualnego dysku twardego - stworzymy wtedy maszynę bez dysku która się nie odpali (wybieramy gdy mamy specjalną kartę sieciową i nasz komputer łączy się z serwerem i pobiera z niego system operacyjny.

2022-05-02 17:36 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +- Guided-use entire disk - Przypisywanie 1 partycji na całym dysku (wybieramy, gdzy zależy nam na czasie i nie chcemy się bawić w ręczne partycjonowanie. Opcja ta usunie wszystkie wcześniej
- Guided-use entire disk - Automatyczne przypisywanie partycji na dysku . Po wybraniu opcji mamy 3 możliwości:
*Zapisanie wszystkiego na jednej partycji (rekomendowane dla nowych użytkowników)
*Wydzielenie partycji /home
*Wydzielenie partycji /home /var oraz /tmp
- Guided-use entire disk and set up LVM - To samo co powyżej, natomiast z ustawieniem LVM (opcja umożliwiająca nam połączyć kilka dysków w 1 wirtualny dysk)
 Dodatkowo w przypadku wybrania tej opcji musimy wybrać czy chemy aby nasze woluminy były zaczyfrowane za pomocą luks(specyfikacja 
szyfrowania dysky twardego przeznaczona dla linux), oraz w przypadku wybrania szyfrowania należy podać hasło, które będziemy wprowadzać przy uruchomieniu systemu)

2022-05-02 18:35 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +	oraz nadaję się również dla słabszych komputerów. Jeżeli chodzi o wydajność i zużycie mocy obliczeniowej jest ono na średnim poziomie. Dodatkowo
Posiada on nowoczesny interfejs oraz jest prosty w użyciu. Mamy możliwość rozszerzenia jego funkcjonalności poprzez rozszerzenia Shell Extensions oraz mamy 
	możliwość łatwego dostosowania jego wyglądu. Posiada on stosunkowo małe zużycie mocy obliczeniowej oraz zarządzanie powyżej wymienionymi rozszerzeniami nie jest zbyt intuicyjne.

2022-05-02 18:36 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +	Minimalne wymagania:
Jest on intuicyjny oraz łatwy w obsłudze, posiada dużo możliwości personalizacji, pójdzie na słabszym komputerze oraz ma małe zużycie mocy obliczeniowej (minimalnie większe od GNOME)

2022-05-03 20:10 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia2/zadanie3.txt
> +-PWD 		- Zmienna do używania w skryptach pokazuje ściezke w skrypcie
wywołanie $(pwd) otwiera nową powłokę
Wywołanie zmiennej $PWD jest wydajniejsze, ponieważ nie otwieramy nowej powłoki
Dodatkowo zalecane jest używanie $PWD, ponieważ nie zawsze powłoka obsługuje $(pwd) co zdarza się dość często, $PWD daje nam zawsze "bardziej aktualne informacje", $(pwd) nie działa gdy bieżący katalog kończy się znakiem nowej linii

Nie jestem pewien czy o to chodziło, natomiast nie znalazłem nigdzie więcej informacji na ten temat

2022-05-03 20:32 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia2/zadanie3.txt
> +-USER 	- Wyświetlanie naszego loginu
-USER 	- Wyświetlanie naszego loginu - Przydatne gdy piszemy skrypt który ma wyświetlać jakieś informacje na temat użytkowników 
-HOSTNAME 	- Wyświetlanie nazwe naszego hosta - Przydatne gdy chcemy napisać skrypt, w którym będziemy modyfikować aliasy naszej domeny, pobierać adresy IP w naszej sieci lub wyliczać wszystkie skonfigurowane adresy na interfejsach sieciowych
-OSTYPE 	- Wyświetla wersje naszego systemu operacyjnego - Przydatne gdy piszemy skrypt pod konkretny system operacyjny

2022-05-03 22:38 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia2/zadanie2.txt
> +Otworzył się nam nowy bash/nowa powłoka po chwili ładowania.
Przypisaliśmy do zmiennej x wartość tekst, wyświetliliśmy ją komendą echo, oraz następnie komendą bash otworzyliśmy nową powłokę , po czym nie mogliśmy już wywołać naszej zmiennej x, ponieważ jest to zmienna lokalna która jest dostępna tylko i wyłącznie w 1 powłoce (w przeciwieństwie do globalnej)

2022-05-04 13:20 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia2/zadanie4.txt
> +Nie wypsiuje informacji w liniach tylko jednym ciągiem
Po krótkim testowaniu można zauważyć iż jeżeli przypiszemy komendę ls-l do zmiennej w terminalu (np. zmienna1='ls -l') i następnie ją wywołamy (NIE PRZEZ ECHO), czyli wpisująć $zmienna1 to dostajemy oczekiwany wynik.

2022-05-04 16:09 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia2/zadanie6.txt
> + echo "$1  ma kota, a kot ma" $1 | sed s/a$/ę/g | sed 's/\([^ę]\)$/\1a/g'
#!/bin/bash
 echo "$1  ma kota, a kot ma" $1 | sed s/a$/ę/g | sed 's/\([^ę]\)$/\1a/g'
 Przy zmiennej $1 mamy imię żenśkie (w tym przypadku Ala), a następnie sed zamienia nam końcówkę 
zastępując podanym łancuchem(ę) wszystkie znalezione w buforze wyrażenia(a$) oraz  wyświetla numer linii(g na końcu)

2022-05-04 16:11 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +- Show Cylinder/Head/Selector Information - Pokazuje nam wszelkie informację na temat naszeych dysków (Cylindry, Głowice)
jeżeli mamy informację na temat głowic i dzięki tej informacji możemy zoptymalizować operacje na dysku (możemy tak podzielić partycję aby nasza konfiguracja działała wydajniej)

2022-05-04 17:16 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +-Mount point - punkt montowania(/)
Również nie widzę nigdzie informacji na ten temat. Jedyne co znalazłem to to, że punkt montowania to katalog (zazwyczaj pusty) w którym zamontowany jest dodatkowy system plików . A z racji iż będziemy ustawiali jeden rodzaj systemu plików to punkt montowania jest ustawiony na domyślny (/)

2022-05-04 18:07 UTC, s25938pj commented on s25938pj-JakubKwasniak/zajecia1/instalacja_debiana_linux.txt
> +Ext4 journaling file system - Następca ext3. Obecnie najpopularniejszy system plików dla systemów Linuxa.
Ext4 journaling file system - Następca ext3. Obecnie najpopularniejszy system plików dla systemów Linuxa.
jest on dużo wydajniejszy oraz posiada kompatybliność wsteczną względem ext3. Możemy m.in wyłączyć w nim funkcję księgowania, co poprawi wydajność,
Limit systemu plików został zwiększony z 16TB do 1EB  (1EB = 1024PB, 1PB = 1024TB), limit plików z 2TB do 16TB, limit podkatalogów został rozszerzony z 32,768 do nieograniczonego,
Ext4 w przeciwieństwo do ext3 obsługuje defreagmentacje oraz obsługuje pełne indeksowanie katalogów

Ext3 journaling file system - system plików oparty na ext2. Domyśdlny dla większości systemów Linux (na jądrze od 2.4 do 2.6).
Główną zmianą jaka zaszła w Ext3 to wprowadzenie księgowania plików (pliki nie są od razu zapisywane na dysku, lecz w kronice, 
dzięki czemu jest mniejsze prawdopobobieństwo na utratę danych). Jest on bardzo prosty w implementacji, obciąża w małym stopniu
procesor oraz jest kompatibylny z ext2. Do jego wad można zaliczyć ograniczoną wielkość partycji (32TB), zmiana wielkości partycji
nie jest taka prosta, ponieważ należy wpierw ją odmontować oraz zamienić na ext2 (w innym przypadku stracimy dane)

Ext2 file system - drugi rozszerzony system plików dla systemu Linux. Rozpoznanie uszkodzeń systemu następuje podczas startu. 
Maksymalna wielkość partycji w tym systemie plików to około 4TB, pliki mogą mięć rozmiar maksymalnie 2TB oraz mogą mieć
maksymalnie 255 znaków wielkości. Dodatkowo zawiera mechanizm zapobiegający znacznej fragmentacji danych, co było częstym 
zjawiskiem w poprzednich wersjach. Kolejną zaletą sa tzw. wolne pola w strukturach danych. To dzięki nim możliwa jest
konwersja "w locie" do systemu ext3 (wykorzystuje część z nich do przechowania swoich danych).

btrfs journaling file system - system plików copy-to-copy w stylu logowania. 
Zamiast zapisywać od razu w bloku są one najpierw tworzone w nowej lokalizacji, a następnie łączy się je.
Jest to nowoczesny system plików o otwartym kodzie źródłowym. Dzięki kopiowaniu i modyfikowaniu danych do innej
lokalizacji mamy mniejsze ryzyko uszkodzenia danych w razie przerwy w dostawie prądu. Podczas modyfikacji oryginalne 
dane są zachowywane i pozostają niezmienione. BTFRS obsługuje RAID 0, 1, oraz 10, daje nam możliwośc zmian rozmiaru 
plików wtedy, gdy jest on w trybie online, działa on bardzo dobrze z dyskami SSD (zwiększa ich wydajność, tym samym ich żywotność)
Jeśli chodzi o wady to wymieniony powyżej system plików ma tendencję do fragmentowania dużych plików i raz na jakiś czas wymagana będzie defragmentacja. 

JFS journaling file system - 64bitowy system plików z księgowaniem opracowany przez IBM. Jest wykorzystywany w systemach AIX
Posiada on bardzo małe zużycie procesora (mniejsze niż inne systemy plików). Posiada on również mechanizm 
księgowania, przez co jest zalecany w przypadku serwerów.
Według informacji na portalach nie jest on praktycznie Wogóle używany przez osoby spoza firmy IBM.

XFS journaling file system - 64bitowy system plików z księgowaniem przeznaczony głównie do systemu IRIX. 
Pozwala na obsługę dużych dysków twardych. Maksymalny rozmiar patycji jest ośmiokrotnie większy od Ext4 (aż 8EB), a rozmiar
plików wynosi maksymalnie 16TB. Posiada technologie dynamicznego alokowania i węzłów. Obsługuje również większą długość xattr
(64K w porównaniu do 4k w ext4), posiada tzw. grupy alokacji, czyli wewnętrznie system plików jest podzielony na grupy w celu
oddzielnego zarządzania węzłami i wolnym miejscem, co daje skalowalność i równoległośc, dzięki czemu możemy wykonywać więcej 
operacji na tym samym systemie plików. Posiada on również wbudowane narzędzia umożliwiające tworzenie kopii zapasowej
oraz przywracanie zawartości

FAT16 file system - system plików posługujący się 16-bitowym adresowaniem. 
Pierwsze komputery działąjące na systemie DOS miały architekturę 16 bitową
W dzisiejszych czasach jest on używany głównie w kartach pamięci typu flash. W codziennym życiu jest on bardzo rzadko używany
przez zwykłych użytkowników.
Do jego zalet można zaliczyć dobrą wydajność przy woluminach mniejszych niż 256MB oraz posiadanie sporej ilości narzędzi służących
do odzyskiwania i naprawiania uszkodzinych danych. 
Do jego minusów można zaliczyć stałe umiejscowienie bootsectora, maksymalna wielkość woluminu
wynosi jedynie 2GB (w Windows 2000 są to 4GB). Powoduje znaczne straty w wolnej przestrzeni marnując jej jej nawet kilkadziesiąt
procent

FAT32 file system - System plików użyty pierwszy raz w windows 95
W następcy FAT 32 została m.in zwiększona maksymalna wielkość woluminu (z 2GB do 2TB), natomiast standardowo można stworzyć partycje
nie większą niż 32GB, ze względu na root directory (ruchomy katalog główny) jest on bardziej odporny na awarie, w niektórych
przypadkach programy są odpalane nawet 50% szybciej . Jeśli chodzi o minusy to w przypadku awarii nie możemy uruchomić 
komputera za pomocą specjalnej dyskietki startowej sformatowanej np pod systemem FAT16, nie posiada również (w przeciwieństwie
do starszego brata) mechanizmów do odzyskiwania i naprawiania danych. Oraz wbrew pozorom nie używa on 32 bitów jak mówi
nazwa, lecz 28

2022-05-04 18:15 UTC, s25938pj commented
Wydaje mi się że odniosłem się w miarę sił do wszystkich Pana komentarzy. Chciałbym również zapytać się Pana Profesora czy mógłby pan lekko odpuścić te szczegóły . Rozumiemy jak najbardziej że mamy zostać inżynierami, że powinniśmy to wszystko wiedzieć, natomiast w mojej opinii nie da się być alfą i omegą i ledwo co udaję się wszystko nadrobić, ponieważ gdy mamy do zrobienia zadanie z dajmy na to 4 zjazdu a mamy jeszcze mase rzeczy do poprawienia z 1,2, oraz 3 to z biegiem czasu staje się to trochę niewykonalne. Do tego mamy również inne przedmioty które zajmują nam bardzo dużo czasu jeśli chodzi zarówno o zadania, jak i samą naukę.  Chciałbym również nadmienić że większość z nas pracuje w tygodniu i nie ma tyle czasu codziennie aby siedzieć tak długo nad nauką. Jeżeli ma Pan Profesor jakieś sugestie co do powyższej wypowiedzi, lub z czymś się nie zgadza to chętnie podjęlibyśmy dyskusję z Panem na kolejnym zjeździę. Na koniec chciałbym również zaznaczyć że nie są to żadne zażalenia ani roszczenia w Pana stronę, lecz zwykłe przemyślenia.

2022-05-18 18:43 UTC, t0meck-pj approved these changes
Są jeszcze drobne błędy ale powiedzmy, że jest ok.
W kolejnych commitach możesz dodać poprawki.

2022-05-18 18:43 UTC, t0meck-pj commented
Przychylam się do prośby Twojej/Waszej prośby.

2022-05-18 18:43 UTC, merged