Pisanie skrpytów w Bashu laboratorium 2
t0meck-pj/sop2021-22_25c pull request #8
Opened 2022-03-28 22:32 UTC by s25938pj

2022-03-28 23:54 UTC, t0meck-pj commented
Proszę jeszcze raz przeczytać opis w pliku README.md (cały opis od początku pliku)

2022-03-29 01:12 UTC, t0meck-pj requested changes
Opis instalacji jest dobrym początkiem. Trzeba go trochę pozmieniać i umieścić we właściwym miejscu. Podobnie rozwiązania zadań z 2 zajęć.

Proszę także uzupełnić pamiętnik z pierwszych zajęć.

2022-03-29 01:12 UTC, t0meck-pj commented on s25938pj-JakubKwasniak/pamietnik.txt.txt
> +-PS1		- Wyświetla wartości konsoli
Źle

2022-03-29 01:12 UTC, t0meck-pj commented on s25938pj-JakubKwasniak/pamietnik.txt.txt
> +-OSTYPE 	- Wyświetla wersje naszego systemu operacyjnego
Kiedy to może być przydatne?

2022-03-29 01:12 UTC, t0meck-pj commented on s25938pj-JakubKwasniak/pamietnik.txt.txt
> +Ext3 journaling file system - system plików oparty na ext2. Domyśdlny dla większości systemów Linux (na jądrze od 2.4 do 2.6)
Domyśdlny

2022-03-29 01:12 UTC, t0meck-pj commented on s25938pj-JakubKwasniak/pamietnik.txt.txt
> +Ext2 file system - drugi rozszerzony system plików dla systemu Linux. Rozpoznanie uszkoczeń systemu następuje podczas startu.
uszkoczeń

2022-03-29 01:12 UTC, t0meck-pj commented on s25938pj-JakubKwasniak/pamietnik.txt.txt
> +-Automatically partition the free space - Automatyczne tworzeniej partycji na wolnym miejscu
Kiedy używać tej opcji a kiedy nie?
Tzn już wiemy, że nigdy więcej nie będziecie instalować linuxa graficznie ani automatycznie partycjonując dysk więc raczej dlaczego tej opcji NIE używać?

2022-03-29 01:12 UTC, t0meck-pj commented on s25938pj-JakubKwasniak/pamietnik.txt.txt
> +-Configure the Logical Volume Manager - Konfiguracja Menedżera woluminów logicznych
Co to jest LVM?
Kiedy go stosować?
Co on daje?

2022-03-29 01:12 UTC, t0meck-pj commented on s25938pj-JakubKwasniak/pamietnik.txt.txt
> +-Configure ISCII volumes - Konfiguracja woluminów ISCII (ISCII - schemat kodowania reprezentujący różne systemy pisma w Indiach)
Do poprawy

2022-03-29 01:12 UTC, t0meck-pj commented on s25938pj-JakubKwasniak/pamietnik.txt.txt
> +Ustawiamy partycję podstawową o pojemności o 8GB Mniejszą od tej pamięci jaka nam wyskakuje (Aby mieć miejsce potem na logiczną), ustawiamy ją na początku (Beginning)
- Jakie są typy partycji?
- Ile można utworzyć partycji każdego typu na dysku i z czego to wynika?
- Jakie są ograniczenia odnośnie partycji? (hint: bootowanie)

2022-03-29 01:12 UTC, t0meck-pj commented on s25938pj-JakubKwasniak/pamietnik.txt.txt
> +-Bootable flag - flaga startowa (off)
- Co to jest za flaga?
- Po co jest używana?
- Kiedy należy ją włączać?

2022-03-29 01:12 UTC, t0meck-pj commented on s25938pj-JakubKwasniak/pamietnik.txt.txt
> +Mamy już utworzoną pierwszą partycję podstawową . Klikamy znowu w zakładkę free space/create a new partition/przypisujemy 8GB i ustawiamy partycję tym razem na logiczną
Dlaczego wybierasz partycję logiczną?
Jakimi zasadami należy się kierować przy wyborze typu partycji na dysku?

2022-03-29 01:13 UTC, t0meck-pj commented
Proszę poprawić błędy, uzupełnić braki, przenieść treść do właściwych plików i wystawić kolejny PR.
W razie problemów proszę o kontakt mailowy.

2022-03-29 01:13 UTC, closed without merging

2022-03-29 13:52 UTC, s25938pj commented
Skontaktowałem się proszę Pana z kolegami z grupy i zobaczyłem że kolega
Jan Wolski zamiast "zainspirować się" moim sprawozdaniem i napisać je po
przeczytaniu własnymi słowami zacomitował mój plik który mu wysłałem.
Autorem sprawozdania jestem ja i jeżeli ktoś popełnił plagiat to kolega
nieumyślnie.
Mogę dodatkowo pokazać Panu notatki z zajęć które mam w zeszycie i które
pokrywają się z moim sprawozdaniem
Proszę o odpowiedź
Kwaśniak Jakub

wt., 29 mar 2022 o 03:13 t0meck-pj ***@***.***> napisał(a):

> Closed #8 <https://github.com/t0meck-pj/sop2021-22_25c/pull/8>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/t0meck-pj/sop2021-22_25c/pull/8#event-6322680269>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AV7ROPE6HEY3QFMV7XYVME3VCJKL3ANCNFSM5R4RWSIQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>